max_width = 100
use_small_heuristics = "Max"
newline_style = "Unix"
# fn_params_layout = "Compressed"
error_on_unformatted = true
error_on_line_overflow = true

# Unstable
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_impl_items = true
wrap_comments = true
